version: '2'

services:
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
    ports:
     - "6379:6379"

  app:
    image: node:latest
    volumes:
      - ../../:/cimis-mobile
    links:
      - redis
    environment:
      - CIMIS_MOBILE_ENV=development
      - CIMIS_DOCKER=true
    ports:
      - "8080:8080"
    # command: node /cimis-mobile/server
    command: tail -f /dev/null

volumes:
  redisdata:
    driver: local