version: '2'

services:
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
    ports:
     - "6379:6379"

  app:
    image: node:latest
    volumes:
      - ../../:/cimis-mobile
    links:
      - redis
    ports:
      - "8080:8080"
    command: bash -c "cd cimis-mobile && npm run docker-dev"
    # command: bash -c "cd cimis-mobile && node server.js --docker"

volumes:
  redisdata:
    driver: local