version: '2'

services:
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

  app:
    build: ../..
    links:
      - redis
    ports:
      - "8080:8080"

volumes:
  redisdata:
    driver: local