version: '2'

services:
  redis:
    image: redis:latest
    volumes:
      - redisdata:/data

  app:
    build: ../..
    links:
      - redis
    environment:
      - CIMIS_MOBILE_ENV=production
      - CIMIS_MOBILE_PORT=8000
    ports:
      - "8000:8000"

volumes:
  redisdata:
    driver: local